version: "3.8"
services:
  portainer:
    image: portainer/portainer:latest
    restart: always
    container_name: portainer
    ports:
    - "9000:9000"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - portainer:/data
    networks:
    - internet
    - intranet
    
  mongo:
    image: mongo
    restart: always
    container_name: mongo
    ports:
    - "27017:27017"
    networks:
    - intranet
    volumes:
    - database:/data
    environment:
      MONGO_INITDB_ROOT_USERNAME: 
      MONGO_INITDB_ROOT_PASSWORD: 

  mongo-express:
    image: mongo-express
    restart: always
    container_name: mongo-express
    ports:
    - "8081:8081"
    networks:
    - internet
    - intranet
    depends_on:
    - mongo
    environment:
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: 
      ME_CONFIG_MONGODB_ADMINPASSWORD: 
      ME_CONFIG_BASICAUTH_USERNAME: 
      ME_CONFIG_BASICAUTH_PASSWORD: 

volumes:
  portainer:
  database:

networks:
  intranet:
    internal: true
    driver: overlay
    name: intranet
  internet:
    name: internet