version: "3.8"
services:
  portainer:
    image: portainer/portainer:latest
    restart: always
    container_name: portainer
    ports:
    - "9000:9000"
    volumes:
    - /var/run/docker.sock:/var/run/docker.sock
    - portainer:/data
    networks:
    - internet
    - intranet
    
volumes:
  portainer:

networks:
  intranet:
    name: intranet
  internet:
    name: internet